//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReliableCabs.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashCollected
    {
        public int CashAmountId { get; set; }
        public Nullable<decimal> CashAmount { get; set; }
        public string RefNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
