//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReliableCabs.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int ClientId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string DriverLicenceNo { get; set; }
        public string BankDetails { get; set; }
        public string SimNumber { get; set; }
        public string NamePlateNumber { get; set; }
        public string PhysicalAddress { get; set; }
        public string OtherInfo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
