//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReliableCabs.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanTran
    {
        public int LoanTransId { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> SubTransId { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<decimal> LoanCashAmount { get; set; }
        public Nullable<decimal> LoanChequeAmount { get; set; }
        public string LoanChequeNumber { get; set; }
        public Nullable<decimal> LoanOnlineAmount { get; set; }
        public Nullable<decimal> LoanToDriver { get; set; }
        public string RentRemarks { get; set; }
    }
}
