//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReliableCabs.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodType
    {
        public int PeriodTypeId { get; set; }
        public string PeriodType1 { get; set; }
    }
}
