//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReliableCabs.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentHold
    {
        public int RentHoldID { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<System.DateTime> RentHoldStartdate { get; set; }
        public Nullable<System.DateTime> RentHoldStopdate { get; set; }
        public Nullable<decimal> RentoutstandingAmt { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
    }
}
