//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReliableCabs.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public int SubscriptionId { get; set; }
        public int ClientId { get; set; }
        public string Terminal { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> SubscriptionStartDate { get; set; }
        public Nullable<decimal> RentAmount { get; set; }
        public Nullable<int> PeriodTypeId { get; set; }
        public Nullable<System.DateTime> SubscriptionEndDate { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> EfposServiceCharge { get; set; }
        public Nullable<decimal> ChitsCommission { get; set; }
        public Nullable<decimal> LoanAmount { get; set; }
        public Nullable<System.DateTime> LoanDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
